[workspace]
members = ["crates/core", "crates/model", "crates/cli"]
default-members = ["crates/cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/yexiyue/castglean"
publish = false

[workspace.dependencies]
castglean-core = { path = "crates/core" }
castglean-model = { path = "crates/model" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"
schemars = "1"
tokio = { version = "1", features = ["macros", "time", "sync"] }
tokio-util = { version = "0.7", features = ["rt"] }
genai = "=0.7.0-rc.1"
dotenvy = "0.15"
url = "2"

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
