//! Safe, deterministic feedback. No paths or IDs copied from rejected values.
use crate::SegmentId;
use serde::Serialize;
use std::fmt;

/// Stable categories for suggestion failures, independent of provider errors.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SuggestionIssueCode {
    /// Response is not syntactically valid JSON.
    InvalidJson,
    /// JSON does not match the suggestion DTO.
    InvalidStructure,
    /// New identity is blank, duplicated or has blank names.
    InvalidIdentity,
    /// Required evidence is absent or outside visible input.
    InvalidEvidence,
    /// A segment is outside the target window.
    OutsideTarget,
    /// A target appears more than once.
    DuplicateTarget,
    /// A target has no annotation.
    MissingTarget,
    /// Speech or thought lacks attribution.
    MissingAttribution,
    /// A temporary identity was not declared in this candidate.
    UndeclaredIdentity,
    /// An existing identity was not supplied in context.
    UnknownIdentity,
    /// Ambiguity requires at least two distinct identities.
    InvalidCandidates,
    /// Quotation mode requires supporting source quotations.
    MissingQuotation,
    /// Blank, duplicate, oversized or incorrectly scoped quotation.
    InvalidQuotation,
    /// Quotation is absent from the specified source segment.
    QuotationNotFound,
    /// Quotation occurs more than once, including overlapping matches.
    QuotationNotUnique,
}
impl SuggestionIssueCode {
    /// Stable machine-readable category.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::InvalidJson => "invalid_json",
            Self::InvalidStructure => "invalid_structure",
            Self::InvalidIdentity => "invalid_identity",
            Self::InvalidEvidence => "invalid_evidence",
            Self::OutsideTarget => "outside_target",
            Self::DuplicateTarget => "duplicate_target",
            Self::MissingTarget => "missing_target",
            Self::MissingAttribution => "missing_attribution",
            Self::UndeclaredIdentity => "undeclared_identity",
            Self::UnknownIdentity => "unknown_identity",
            Self::InvalidCandidates => "invalid_candidates",
            Self::MissingQuotation => "missing_quotation",
            Self::InvalidQuotation => "invalid_quotation",
            Self::QuotationNotFound => "quotation_not_found",
            Self::QuotationNotUnique => "quotation_not_unique",
        }
    }
    pub(super) fn message(self) -> &'static str {
        match self {
            Self::InvalidJson => "invalid JSON syntax",
            Self::InvalidStructure => "invalid suggestion structure",
            Self::InvalidIdentity => "invalid or duplicate new identity",
            Self::InvalidEvidence => "missing or invisible evidence",
            Self::OutsideTarget => "annotation outside target window",
            Self::DuplicateTarget => "duplicate target annotation",
            Self::MissingTarget => "missing target annotation",
            Self::MissingAttribution => "speech and thought require attribution",
            Self::UndeclaredIdentity => "undeclared temporary identity",
            Self::UnknownIdentity => "unknown existing identity",
            Self::InvalidCandidates => "ambiguous attribution requires distinct candidates",
            Self::MissingQuotation => "supporting source quotation required",
            Self::InvalidQuotation => "invalid or incorrectly scoped source quotation",
            Self::QuotationNotFound => "source quotation not found in evidence segment",
            Self::QuotationNotUnique => {
                "source quotation must occur exactly once in evidence segment"
            }
        }
    }
}

/// Application-generated feedback without source text or rejected model values.
///
/// Fields are read-only so the validator controls feedback provenance.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, schemars::JsonSchema)]
pub struct SuggestionIssue {
    code: SuggestionIssueCode,
    path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    segment_id: Option<SegmentId>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    missing_segment_ids: Vec<SegmentId>,
}
impl SuggestionIssue {
    /// Deterministic failure category.
    pub fn code(&self) -> SuggestionIssueCode {
        self.code
    }
    /// JSON-pointer-style position generated by the application.
    pub fn path(&self) -> &str {
        &self.path
    }
    /// A supplied target ID, never an arbitrary rejected ID.
    pub fn segment_id(&self) -> Option<&SegmentId> {
        self.segment_id.as_ref()
    }
    /// All missing source-generated targets, in source order.
    pub fn missing_segment_ids(&self) -> &[SegmentId] {
        &self.missing_segment_ids
    }
    pub(super) fn with_missing(mut self, ids: Vec<SegmentId>) -> Self {
        self.missing_segment_ids = ids;
        self
    }
    pub(super) fn new(code: SuggestionIssueCode, path: impl Into<String>) -> Self {
        Self {
            code,
            path: path.into(),
            segment_id: None,
            missing_segment_ids: vec![],
        }
    }
    pub(super) fn for_segment(mut self, id: &SegmentId) -> Self {
        self.segment_id = Some(id.clone());
        self
    }
}
impl fmt::Display for SuggestionIssue {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // IDs are available through accessors/feedback, not echoed in diagnostics.
        if self.path.is_empty() {
            f.write_str(self.code.message())
        } else {
            write!(f, "{} at {}", self.code.message(), self.path)
        }
    }
}
