//! Safe, deterministic feedback. No paths or IDs copied from rejected values.
use crate::SegmentId;
use serde::Serialize;
use std::fmt;

/// Stable categories for suggestion failures, independent of provider errors.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum SuggestionIssueCode {
    /// Response is not syntactically valid JSON.
    InvalidJson,
    /// JSON does not match the suggestion DTO.
    InvalidStructure,
    /// New identity is blank, duplicated or has blank names.
    InvalidIdentity,
    /// Required evidence is absent or outside visible input.
    InvalidEvidence,
    /// A segment is outside the target window.
    OutsideTarget,
    /// A target appears more than once.
    DuplicateTarget,
    /// A target has no annotation.
    MissingTarget,
    /// Speech or thought lacks attribution.
    MissingAttribution,
    /// A temporary identity was not declared in this candidate.
    UndeclaredIdentity,
    /// An existing identity was not supplied in context.
    UnknownIdentity,
    /// Ambiguity requires at least two distinct identities.
    InvalidCandidates,
}
impl SuggestionIssueCode {
    pub(super) fn message(self) -> &'static str {
        match self {
            Self::InvalidJson => "invalid JSON syntax",
            Self::InvalidStructure => "invalid suggestion structure",
            Self::InvalidIdentity => "invalid or duplicate new identity",
            Self::InvalidEvidence => "missing or invisible evidence",
            Self::OutsideTarget => "annotation outside target window",
            Self::DuplicateTarget => "duplicate target annotation",
            Self::MissingTarget => "missing target annotation",
            Self::MissingAttribution => "speech and thought require attribution",
            Self::UndeclaredIdentity => "undeclared temporary identity",
            Self::UnknownIdentity => "unknown existing identity",
            Self::InvalidCandidates => "ambiguous attribution requires distinct candidates",
        }
    }
}

/// Application-generated feedback without source text or rejected model values.
///
/// Fields are read-only so the validator controls feedback provenance.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct SuggestionIssue {
    code: SuggestionIssueCode,
    path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    segment_id: Option<SegmentId>,
}
impl SuggestionIssue {
    /// Deterministic failure category.
    pub fn code(&self) -> SuggestionIssueCode {
        self.code
    }
    /// JSON-pointer-style position generated by the application.
    pub fn path(&self) -> &str {
        &self.path
    }
    /// A supplied target ID, never an arbitrary rejected ID.
    pub fn segment_id(&self) -> Option<&SegmentId> {
        self.segment_id.as_ref()
    }
    pub(super) fn new(code: SuggestionIssueCode, path: impl Into<String>) -> Self {
        Self {
            code,
            path: path.into(),
            segment_id: None,
        }
    }
    pub(super) fn for_segment(mut self, id: &SegmentId) -> Self {
        self.segment_id = Some(id.clone());
        self
    }
}
impl fmt::Display for SuggestionIssue {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // IDs are available through accessors/feedback, not echoed in diagnostics.
        if self.path.is_empty() {
            f.write_str(self.code.message())
        } else {
            write!(f, "{} at {}", self.code.message(), self.path)
        }
    }
}
